services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  db-m1:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ingestao
    ports:
      - "5433:5432"
    volumes:
      - db-m1-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ingestao"]
      interval: 10s
      timeout: 5s
      retries: 10

  m1:
    build: .
    environment:
      DATABASE_URL: jdbc:postgresql://db-m1:5432/ingestao
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-m1:
        condition: service_healthy

volumes:
  db-m1-data: